=== JOstapjuk/VeeArvedXSLT/lugumised.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="veearvesti">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="building">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="period">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="lugumised">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="kuld_m3" type="xs:decimal" />
													<xs:element name="soe_m3" type="xs:decimal" />
												</xs:sequence>
												<xs:attribute name="korter" type="xs:string" use="required" />
												<xs:attribute name="nimi" type="xs:string" use="required" />
												<xs:attribute name="kuupaev" type="xs:date" use="required" />
												<xs:attribute name="makstud" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="year" type="xs:unsignedShort" use="required" />
									<xs:attribute name="month" type="xs:unsignedByte" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required" />
						<xs:attribute name="address" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JOstapjuk/VeeArvedXSLT/lugumised.xml
<?xml version="1.0" encoding="utf-8"?>
<veearvesti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="lugumised.xsd">
	<building id="B1" address="Tallinna 10">
		<period year="2025" month="10">
			<lugumised korter="1A" nimi="Jaan Tamm" kuupaev="2025-10-15" makstud="ei">
				<kuld_m3>2.34</kuld_m3>
				<soe_m3>1.12</soe_m3>
			</lugumised>
			<lugumised korter="2B" nimi="Mari Maasikas" kuupaev="2025-10-16" makstud="jah">
				<kuld_m3>3.00</kuld_m3>
				<soe_m3>2.50</soe_m3>
			</lugumised>
		</period>

		<period year="2025" month="11">
			<lugumised korter="1A" nimi="Jaan Tamm" kuupaev="2025-11-15" makstud="jah">
				<kuld_m3>2.50</kuld_m3>
				<soe_m3>1.20</soe_m3>
			</lugumised>
		</period>
	</building>

	<building id="B2" address="Pargi 5">
		<period year="2025" month="11">
			<lugumised korter="10" nimi="Kati Kask" kuupaev="2025-11-10" makstud="ei">
				<kuld_m3>1.00</kuld_m3>
				<soe_m3>0.80</soe_m3>
			</lugumised>
		</period>
	</building>
</veearvesti>
